### PR TITLE
Remove nav-bar links and welcome text in list page

### PR DESCRIPTION
**Pull request by jaigouk**
- Removed links in the navbar-brand and navbar-text elements
- Removed welcome message and displayed root of Breadcrumbs in list page

Signed-off-by: Jaigouk Kim <ping@jaigouk.kim>

# Description

Noted above ^

# Types of changes

  - [x] Bug fix (non-breaking change which fixes an issue)
  - [ ] New feature (non-breaking change which adds functionality)
  - [ ] Breaking change (fix or feature that would cause existing functionality to change)

# Checklist:

  - [x] My code follows the code style of this project.
  - [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly.
  - [x] I've read the CONTRIBUTION guide
  - [x] I have signed-off my commits with git commit -s
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by kenfdev** [comment]
Thanks a lot @jaigouk !

Currently, this codebase is managed in 2 places (which I want to quit as soon as it gets officially released)

Could you add a PR [here](https://github.com/kenfdev/openfaas-cloud/tree/144-react-dashboard), too?

I don't want to take up your great work.

**Comment by alexellis** [comment]
Better to do rebase than commit for future reference.

**Comment by jaigouk** [comment]
@kenfdev i still need to dig into openfaas-cloud. I don't know how of-cloud-dashboard is included in openfaas-cloud. This PR was a quick fix based on chat on slack. It looked like very urgent. so i just focused on react part only.

**Comment by kenfdev** [comment]
@jaigouk The code is almost exactly the same.

https://github.com/kenfdev/openfaas-cloud/tree/144-react-dashboard/dashboard/client

It's managed above. You can create the same PR there. Please don't forget to hit `make` to create the new assets. (Feel free to ping me on slack!)

**Pull request merged**
